# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - polyglot-stem-buddy


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '~22'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build 
        env:
          VITE_FEEDBACK_FORM_BASE_URL: ${{ secrets.VITE_FEEDBACK_FORM_BASE_URL }} # Pull from GitHub Secrets
          VITE_FEEDBACK_FORM_FIELD_AGE_GROUP: ${{ secrets.VITE_FEEDBACK_FORM_FIELD_AGE_GROUP }} 
          VITE_FEEDBACK_FORM_FIELD_LANGUAGE: ${{ secrets.VITE_FEEDBACK_FORM_FIELD_LANGUAGE }} 
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Create deployment package
        run: |
          # Create clean deployment directory
          mkdir deploy-package 

          # Copy server files 
          cp -r src/services deploy-package/
          cp package.json deploy-package/
          cp web.config deploy-package/

          # Copy built frontend
          cp -r dist deploy-package/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EF99FE480A346CC92C6AEDD7DE6C55C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6B37BD4E8134AC5B07BF3F9CB581D4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01B27BCD8F9D44BFB65F5039ECD3633D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'polyglot-stem-buddy'
          slot-name: 'Production'
          package: ./deploy-package
          
